# Form implementation generated from reading ui file 'editables/dialog_colores.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_DialogColores(object):
    def setupUi(self, DialogColores):
        DialogColores.setObjectName("DialogColores")
        DialogColores.resize(460, 350)
        DialogColores.setMinimumSize(QtCore.QSize(460, 350))
        DialogColores.setStyleSheet("QDialog#DialogColores, QWidget {\n"
"    background-color: #081120;\n"
"    color: #e6edf7;\n"
"    font-family: \"Segoe UI\";\n"
"    font-size: 11pt;\n"
"}\n"
"\n"
"QWidget#dlgMainContainer {\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"QWidget#dlgTitleCard,\n"
"QFrame#dlgButtonsRow,\n"
"QFrame#dlgChecksRow {\n"
"    background-color: #111c2e;\n"
"    border: 1px solid #24344c;\n"
"    border-radius: 16px;\n"
"}\n"
"\n"
"/* Título */\n"
"QLabel#lblDialogTitulo {\n"
"    color: #f8fbff;\n"
"    font-size: 16pt;\n"
"    font-weight: 700;\n"
"    background: transparent;\n"
"    border: none;\n"
"}\n"
"\n"
"/* Descripción */\n"
"QLabel#lblDialogDescripcion {\n"
"    color: #91a4bf;\n"
"    font-size: 10.5pt;\n"
"    background: transparent;\n"
"    border: none;\n"
"}\n"
"\n"
"/* Checkboxes */\n"
"QCheckBox {\n"
"    color: #e6edf7;\n"
"    spacing: 8px;\n"
"    background: transparent;\n"
"}\n"
"\n"
"QCheckBox::indicator {\n"
"    width: 18px;\n"
"    height: 18px;\n"
"    border-radius: 4px;\n"
"    border: 1px solid #385174;\n"
"    background-color: #0a1423;\n"
"}\n"
"\n"
"QCheckBox::indicator:hover {\n"
"    border: 1px solid #4a8cff;\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    background-color: #4a8cff;\n"
"    border: 1px solid #4a8cff;\n"
"}\n"
"\n"
"/* Botones */\n"
"QPushButton {\n"
"    background-color: #4a8cff;\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 12px;\n"
"    padding: 10px 16px;\n"
"    font-weight: 600;\n"
"    min-height: 22px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #3a7af0;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #2d67d0;\n"
"}\n"
"\n"
"/* Botón cancelar diferente */\n"
"QPushButton#btnCancelarColor {\n"
"    background-color: #1a2638;\n"
"    border: 1px solid #324863;\n"
"    color: #d7e2f0;\n"
"}\n"
"\n"
"QPushButton#btnCancelarColor:hover {\n"
"    background-color: #22324a;\n"
"}\n"
"\n"
"/* Separadores visuales suaves */\n"
"QFrame {\n"
"    color: #24344c;\n"
"}")
        self.verticalLayout = QtWidgets.QVBoxLayout(DialogColores)
        self.verticalLayout.setObjectName("verticalLayout")
        self.dlgMainContainer = QtWidgets.QWidget(parent=DialogColores)
        self.dlgMainContainer.setObjectName("dlgMainContainer")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.dlgMainContainer)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.dlgTitleCard = QtWidgets.QWidget(parent=self.dlgMainContainer)
        self.dlgTitleCard.setObjectName("dlgTitleCard")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.dlgTitleCard)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.lblDialogTitulo = QtWidgets.QLabel(parent=self.dlgTitleCard)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        font.setBold(True)
        self.lblDialogTitulo.setFont(font)
        self.lblDialogTitulo.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblDialogTitulo.setObjectName("lblDialogTitulo")
        self.verticalLayout_3.addWidget(self.lblDialogTitulo)
        self.lblDialogDescripcion = QtWidgets.QLabel(parent=self.dlgTitleCard)
        self.lblDialogDescripcion.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblDialogDescripcion.setWordWrap(True)
        self.lblDialogDescripcion.setObjectName("lblDialogDescripcion")
        self.verticalLayout_3.addWidget(self.lblDialogDescripcion)
        self.verticalLayout_2.addWidget(self.dlgTitleCard)
        self.dlgChecksRow = QtWidgets.QFrame(parent=self.dlgMainContainer)
        self.dlgChecksRow.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.dlgChecksRow.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.dlgChecksRow.setObjectName("dlgChecksRow")
        self.gridLayout = QtWidgets.QGridLayout(self.dlgChecksRow)
        self.gridLayout.setObjectName("gridLayout")
        self.chkAzul = QtWidgets.QCheckBox(parent=self.dlgChecksRow)
        self.chkAzul.setStyleSheet("QCheckBox {\n"
"    color: #e6edf7;\n"
"    spacing: 8px;\n"
"    background: transparent;\n"
"}\n"
"\n"
"QCheckBox::indicator {\n"
"    width: 18px;\n"
"    height: 18px;\n"
"    border-radius: 4px;\n"
"    border: 1px solid #385174;\n"
"    background-color: #0a1423;\n"
"}\n"
"\n"
"QCheckBox::indicator:hover {\n"
"    border: 1px solid #60a5fa;\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    background-color: #3b82f6;\n"
"    border: 1px solid #3b82f6;\n"
"}")
        self.chkAzul.setChecked(True)
        self.chkAzul.setObjectName("chkAzul")
        self.gridLayout.addWidget(self.chkAzul, 0, 3, 1, 1)
        self.chkVerde = QtWidgets.QCheckBox(parent=self.dlgChecksRow)
        self.chkVerde.setStyleSheet("QCheckBox {\n"
"    color: #e6edf7;\n"
"    spacing: 8px;\n"
"    background: transparent;\n"
"}\n"
"\n"
"QCheckBox::indicator {\n"
"    width: 18px;\n"
"    height: 18px;\n"
"    border-radius: 4px;\n"
"    border: 1px solid #385174;\n"
"    background-color: #0a1423;\n"
"}\n"
"\n"
"QCheckBox::indicator:hover {\n"
"    border: 1px solid #4ade80;\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    background-color: #22c55e;\n"
"    border: 1px solid #22c55e;\n"
"}")
        self.chkVerde.setChecked(True)
        self.chkVerde.setObjectName("chkVerde")
        self.gridLayout.addWidget(self.chkVerde, 0, 1, 1, 1)
        self.chkRojo = QtWidgets.QCheckBox(parent=self.dlgChecksRow)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setItalic(False)
        self.chkRojo.setFont(font)
        self.chkRojo.setStyleSheet("QCheckBox {\n"
"    color: #e6edf7;\n"
"    spacing: 8px;\n"
"    background: transparent;\n"
"}\n"
"\n"
"QCheckBox::indicator {\n"
"    width: 18px;\n"
"    height: 18px;\n"
"    border-radius: 4px;\n"
"    border: 1px solid #385174;\n"
"    background-color: #0a1423;\n"
"}\n"
"\n"
"QCheckBox::indicator:hover {\n"
"    border: 1px solid #ff6b6b;\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    background-color: #ef4444;\n"
"    border: 1px solid #ef4444;\n"
"}")
        self.chkRojo.setChecked(True)
        self.chkRojo.setObjectName("chkRojo")
        self.gridLayout.addWidget(self.chkRojo, 0, 0, 1, 1)
        self.chkGris = QtWidgets.QCheckBox(parent=self.dlgChecksRow)
        self.chkGris.setStyleSheet("QCheckBox {\n"
"    color: #e6edf7;\n"
"    spacing: 8px;\n"
"    background: transparent;\n"
"}\n"
"\n"
"QCheckBox::indicator {\n"
"    width: 18px;\n"
"    height: 18px;\n"
"    border-radius: 4px;\n"
"    border: 1px solid #385174;\n"
"    background-color: #0a1423;\n"
"}\n"
"\n"
"QCheckBox::indicator:hover {\n"
"    border: 1px solid #a3a3a3;\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    background-color: #9ca3af;\n"
"    border: 1px solid #9ca3af;\n"
"}")
        self.chkGris.setObjectName("chkGris")
        self.gridLayout.addWidget(self.chkGris, 1, 1, 1, 1)
        self.verticalLayout_2.addWidget(self.dlgChecksRow)
        self.dlgButtonsRow = QtWidgets.QFrame(parent=self.dlgMainContainer)
        self.dlgButtonsRow.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.dlgButtonsRow.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.dlgButtonsRow.setObjectName("dlgButtonsRow")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.dlgButtonsRow)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnCancelarColor = QtWidgets.QPushButton(parent=self.dlgButtonsRow)
        self.btnCancelarColor.setObjectName("btnCancelarColor")
        self.horizontalLayout.addWidget(self.btnCancelarColor)
        self.btnAplicarColor = QtWidgets.QPushButton(parent=self.dlgButtonsRow)
        self.btnAplicarColor.setObjectName("btnAplicarColor")
        self.horizontalLayout.addWidget(self.btnAplicarColor)
        self.verticalLayout_2.addWidget(self.dlgButtonsRow)
        self.verticalLayout.addWidget(self.dlgMainContainer)

        self.retranslateUi(DialogColores)
        QtCore.QMetaObject.connectSlotsByName(DialogColores)

    def retranslateUi(self, DialogColores):
        _translate = QtCore.QCoreApplication.translate
        DialogColores.setWindowTitle(_translate("DialogColores", "Selección de Colores"))
        DialogColores.setAccessibleName(_translate("DialogColores", "Selección de Colores"))
        self.lblDialogTitulo.setText(_translate("DialogColores", "Selección de Colores"))
        self.lblDialogDescripcion.setText(_translate("DialogColores", "Activa o desactiva canales de color. Si activas Gris, los canales activos se convierten a escala de grises."))
        self.chkAzul.setText(_translate("DialogColores", "Azul"))
        self.chkVerde.setText(_translate("DialogColores", "Verde"))
        self.chkRojo.setText(_translate("DialogColores", "Rojo"))
        self.chkGris.setText(_translate("DialogColores", "Escala de Gris"))
        self.dlgButtonsRow.setAccessibleName(_translate("DialogColores", "Selección de Colores"))
        self.btnCancelarColor.setText(_translate("DialogColores", "Cancelar"))
        self.btnAplicarColor.setText(_translate("DialogColores", "Aplicar"))
