# Form implementation generated from reading ui file 'editables/dialog_progreso.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_DialogProgreso(object):
    def setupUi(self, DialogProgreso):
        DialogProgreso.setObjectName("DialogProgreso")
        DialogProgreso.resize(550, 300)
        DialogProgreso.setMinimumSize(QtCore.QSize(550, 300))
        DialogProgreso.setMaximumSize(QtCore.QSize(550, 300))
        DialogProgreso.setStyleSheet("QDialog#DialogProgreso {\n"
"    background-color: #081120;\n"
"    color: #e6edf7;\n"
"    font-family: \"Segoe UI\";\n"
"    font-size: 11pt;\n"
"}\n"
"\n"
"QLabel {\n"
"    background: transparent;\n"
"    border: none;\n"
"    color: #e6edf7;\n"
"}\n"
"\n"
"QLabel#lblTitulo {\n"
"    font-size: 18pt;\n"
"    font-weight: 700;\n"
"    color: #ffffff;\n"
"}\n"
"\n"
"QLabel#lblEstado {\n"
"    color: #91a4bf;\n"
"    font-size: 11pt;\n"
"}\n"
"\n"
"QLabel#lblPorcentaje {\n"
"    font-size: 13pt;\n"
"    font-weight: 600;\n"
"    color: #ffffff;\n"
"}\n"
"\n"
"QLabel#lblTiempo,\n"
"QLabel#lblUltimoEvento {\n"
"    color: #91a4bf;\n"
"    font-size: 10pt;\n"
"}\n"
"\n"
"QProgressBar {\n"
"    background-color: #0a1423;\n"
"    border: 1px solid #385174;\n"
"    border-radius: 12px;\n"
"    height: 24px;\n"
"    text-align: center;\n"
"}\n"
"\n"
"QProgressBar::chunk {\n"
"    background-color: #4a8cff;\n"
"    border-radius: 4px;\n"
"    margin: 0px;\n"
"}\n"
"\n"
"QPushButton {\n"
"    background-color: #381a1a;\n"
"    border: 1px solid #633232;\n"
"    color: #f0d7d7;\n"
"    border-radius: 12px;\n"
"    padding: 10px 18px;\n"
"    font-weight: 600;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #22324a;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #2d67d0;\n"
"}")
        self.verticalLayout = QtWidgets.QVBoxLayout(DialogProgreso)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lblTitulo = QtWidgets.QLabel(parent=DialogProgreso)
        self.lblTitulo.setObjectName("lblTitulo")
        self.verticalLayout.addWidget(self.lblTitulo)
        self.lblEstado = QtWidgets.QLabel(parent=DialogProgreso)
        self.lblEstado.setObjectName("lblEstado")
        self.verticalLayout.addWidget(self.lblEstado)
        self.progressBar = QtWidgets.QProgressBar(parent=DialogProgreso)
        self.progressBar.setProperty("value", 24)
        self.progressBar.setTextVisible(False)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout.addWidget(self.progressBar)
        self.lblPorcentaje = QtWidgets.QLabel(parent=DialogProgreso)
        self.lblPorcentaje.setObjectName("lblPorcentaje")
        self.verticalLayout.addWidget(self.lblPorcentaje)
        self.lblTiempo = QtWidgets.QLabel(parent=DialogProgreso)
        self.lblTiempo.setObjectName("lblTiempo")
        self.verticalLayout.addWidget(self.lblTiempo)
        self.lblUltimoEvento = QtWidgets.QLabel(parent=DialogProgreso)
        self.lblUltimoEvento.setObjectName("lblUltimoEvento")
        self.verticalLayout.addWidget(self.lblUltimoEvento)
        self.btnCancelar = QtWidgets.QPushButton(parent=DialogProgreso)
        self.btnCancelar.setObjectName("btnCancelar")
        self.verticalLayout.addWidget(self.btnCancelar)

        self.retranslateUi(DialogProgreso)
        QtCore.QMetaObject.connectSlotsByName(DialogProgreso)

    def retranslateUi(self, DialogProgreso):
        _translate = QtCore.QCoreApplication.translate
        DialogProgreso.setWindowTitle(_translate("DialogProgreso", "Dialog"))
        self.lblTitulo.setText(_translate("DialogProgreso", "Procesando imágenes"))
        self.lblEstado.setText(_translate("DialogProgreso", "Preparando procesamiento distribuido..."))
        self.lblPorcentaje.setText(_translate("DialogProgreso", "0%"))
        self.lblTiempo.setText(_translate("DialogProgreso", "Tiempo estimado restante: calculando..."))
        self.lblUltimoEvento.setText(_translate("DialogProgreso", "Esperando inicio de trabajos..."))
        self.btnCancelar.setText(_translate("DialogProgreso", "Cancelar"))
