# Form implementation generated from reading ui file 'editables/dialog_seleccion_imagenes.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_DialogSeleccionImagenes(object):
    def setupUi(self, DialogSeleccionImagenes):
        DialogSeleccionImagenes.setObjectName("DialogSeleccionImagenes")
        DialogSeleccionImagenes.resize(460, 350)
        DialogSeleccionImagenes.setMinimumSize(QtCore.QSize(460, 350))
        DialogSeleccionImagenes.setStyleSheet("QDialog#DialogSeleccionImagenes, QWidget {\n"
"    background-color: #081120;\n"
"    color: #e6edf7;\n"
"    font-family: \"Segoe UI\";\n"
"    font-size: 11pt;\n"
"}\n"
"\n"
"QWidget#dlgSelMainContainer {\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"QWidget#dlgSelButtonsRow {\n"
"    background-color: #111c2e;\n"
"    border: 1px solid #24344c;\n"
"    border-radius: 16px;\n"
"}\n"
"\n"
"QLabel#lblSelTitulo {\n"
"    color: #f8fbff;\n"
"    font-size: 15pt;\n"
"    font-weight: 700;\n"
"    background: transparent;\n"
"    border: none;\n"
"}\n"
"\n"
"QListWidget#listSeleccionImagenes {\n"
"    background-color: #0d1727;\n"
"    color: #e6edf7;\n"
"    border: 1px solid #2e4260;\n"
"    border-radius: 16px;\n"
"    padding: 8px;\n"
"    outline: none;\n"
"}\n"
"\n"
"QListWidget#listSeleccionImagenes::item {\n"
"    background-color: #122036;\n"
"    border: 1px solid #233754;\n"
"    border-radius: 10px;\n"
"    margin: 6px;\n"
"    padding: 10px;\n"
"}\n"
"\n"
"QListWidget#listSeleccionImagenes::item:selected {\n"
"    background-color: #1e3f79;\n"
"    border: 1px solid #4a8cff;\n"
"    color: white;\n"
"}\n"
"\n"
"QPushButton {\n"
"    background-color: #4a8cff;\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 12px;\n"
"    padding: 10px 16px;\n"
"    font-weight: 600;\n"
"    min-height: 22px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #3a7af0;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #2d67d0;\n"
"}\n"
"\n"
"QPushButton#btnCancelarSeleccion {\n"
"    background-color: #1a2638;\n"
"    border: 1px solid #324863;\n"
"    color: #d7e2f0;\n"
"}\n"
"\n"
"QPushButton#btnCancelarSeleccion:hover {\n"
"    background-color: #22324a;\n"
"}\n"
"\n"
"/* Scrollbar vertical */\n"
"QScrollBar:vertical {\n"
"    background: transparent;\n"
"    width: 10px;\n"
"    margin: 4px 2px 4px 2px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical {\n"
"    background: #425978;\n"
"    border-radius: 5px;\n"
"    min-height: 30px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical:hover {\n"
"    background: #567095;\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical, QScrollBar::sub-line:vertical {\n"
"    height: 0;\n"
"}\n"
"\n"
"/* Scrollbar horizontal */\n"
"QScrollBar:horizontal {\n"
"    background: transparent;\n"
"    height: 10px;\n"
"    margin: 2px 4px 2px 4px;\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal {\n"
"    background: #425978;\n"
"    border-radius: 5px;\n"
"    min-width: 30px;\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal:hover {\n"
"    background: #567095;\n"
"}\n"
"\n"
"QScrollBar::add-line:horizontal, QScrollBar::sub-line:horizontal {\n"
"    width: 0;\n"
"}")
        self.verticalLayout = QtWidgets.QVBoxLayout(DialogSeleccionImagenes)
        self.verticalLayout.setObjectName("verticalLayout")
        self.dlgSelMainContainer = QtWidgets.QWidget(parent=DialogSeleccionImagenes)
        self.dlgSelMainContainer.setObjectName("dlgSelMainContainer")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.dlgSelMainContainer)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lblSelTitulo = QtWidgets.QLabel(parent=self.dlgSelMainContainer)
        self.lblSelTitulo.setObjectName("lblSelTitulo")
        self.verticalLayout_2.addWidget(self.lblSelTitulo)
        self.listSeleccionImagenes = QtWidgets.QListWidget(parent=self.dlgSelMainContainer)
        self.listSeleccionImagenes.setSelectionMode(QtWidgets.QAbstractItemView.SelectionMode.NoSelection)
        self.listSeleccionImagenes.setObjectName("listSeleccionImagenes")
        self.verticalLayout_2.addWidget(self.listSeleccionImagenes)
        self.dlgSelButtonsRow = QtWidgets.QWidget(parent=self.dlgSelMainContainer)
        self.dlgSelButtonsRow.setObjectName("dlgSelButtonsRow")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.dlgSelButtonsRow)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnCancelarSeleccion = QtWidgets.QPushButton(parent=self.dlgSelButtonsRow)
        self.btnCancelarSeleccion.setObjectName("btnCancelarSeleccion")
        self.horizontalLayout.addWidget(self.btnCancelarSeleccion)
        self.btnAceptarSeleccion = QtWidgets.QPushButton(parent=self.dlgSelButtonsRow)
        self.btnAceptarSeleccion.setObjectName("btnAceptarSeleccion")
        self.horizontalLayout.addWidget(self.btnAceptarSeleccion)
        self.verticalLayout_2.addWidget(self.dlgSelButtonsRow)
        self.verticalLayout.addWidget(self.dlgSelMainContainer)

        self.retranslateUi(DialogSeleccionImagenes)
        QtCore.QMetaObject.connectSlotsByName(DialogSeleccionImagenes)

    def retranslateUi(self, DialogSeleccionImagenes):
        _translate = QtCore.QCoreApplication.translate
        DialogSeleccionImagenes.setWindowTitle(_translate("DialogSeleccionImagenes", "Seleccionar Imágenes"))
        self.lblSelTitulo.setText(_translate("DialogSeleccionImagenes", "Selecciona tus imágenes"))
        self.btnCancelarSeleccion.setText(_translate("DialogSeleccionImagenes", "Cancelar"))
        self.btnAceptarSeleccion.setText(_translate("DialogSeleccionImagenes", "Aplicar"))
