# Form implementation generated from reading ui file 'editables/PixFarm.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1200, 900)
        MainWindow.setMinimumSize(QtCore.QSize(1200, 900))
        MainWindow.setMaximumSize(QtCore.QSize(1200, 900))
        MainWindow.setStyleSheet("QMainWindow, QWidget {\n"
"    background-color: #081120;\n"
"    color: #e6edf7;\n"
"    font-family: \"Segoe UI\";\n"
"    font-size: 11pt;\n"
"}\n"
"\n"
"QWidget#centerHeaderContainer,\n"
"QWidget#rightHeaderContainer {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"}\n"
"\n"
"/* Fondo base de pestañas */\n"
"QTabWidget::pane {\n"
"    border: none;\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"/* Tabs */\n"
"QTabBar::tab {\n"
"    background-color: #18253a;\n"
"    color: #c9d4e5;\n"
"    padding: 10px 22px;\n"
"    min-width: 130px;\n"
"    border-top-left-radius: 12px;\n"
"    border-top-right-radius: 12px;\n"
"    margin-right: 6px;\n"
"    font-weight: 600;\n"
"}\n"
"\n"
"QTabBar::tab:selected {\n"
"    background-color: #4a8cff;\n"
"    color: white;\n"
"}\n"
"\n"
"QTabBar::tab:hover:!selected {\n"
"    background-color: #22324d;\n"
"}\n"
"\n"
"/* Cards principales */\n"
"QFrame#headerCard,\n"
"QFrame#principalPageCard,\n"
"QFrame#aboutPageCard,\n"
"QFrame#leftPanel,\n"
"QFrame#rightPanel,\n"
"QFrame#ruleEditorCard,\n"
"QFrame#executionCard,\n"
"QFrame#infoPanel,\n"
"QFrame#cardProyecto,\n"
"QFrame#cardEquipo {\n"
"    background-color: #111c2e;\n"
"    border: 1px solid #24344c;\n"
"    border-radius: 18px;\n"
"}\n"
"\n"
"/* Header superior */\n"
"QFrame#headerCard {\n"
"    background-color: #132238;\n"
"    border-radius: 18px;\n"
"}\n"
"\n"
"/* Paneles internos un poco más oscuros */\n"
"QFrame#ruleEditorCard,\n"
"QFrame#executionCard,\n"
"QFrame#infoPanel,\n"
"QFrame#cardProyecto,\n"
"QFrame#cardEquipo {\n"
"    background-color: #0d1727;\n"
"    border: 1px solid #2e4260;\n"
"    border-radius: 16px;\n"
"}\n"
"\n"
"/* Labels base */\n"
"QLabel {\n"
"    background: transparent;\n"
"    border: none;\n"
"    color: #e6edf7;\n"
"}\n"
"\n"
"/* Títulos */\n"
"QLabel#lblUploadTitle,\n"
"QLabel#lblRulesTitle,\n"
"QLabel#lblRuleEditorTitle,\n"
"QLabel#lblAboutTitle,\n"
"QLabel#lblProyectoInfo,\n"
"QLabel#lblLogoProyecto,\n"
"QLabel#lblEquipo {\n"
"    color: #f8fbff;\n"
"    font-size: 15pt;\n"
"    font-weight: 700;\n"
"}\n"
"\n"
"/* Subtítulos / apoyo */\n"
"QLabel#lblUploadHint,\n"
"QLabel#lblCantidadImagenes,\n"
"QLabel#lblPreviewNombre,\n"
"QLabel#lblSeleccionImagenesTitulo,\n"
"QLabel#lblAboutSubtitle,\n"
"QLabel#lblResumenSeleccion {\n"
"    color: #91a4bf;\n"
"    font-size: 10.5pt;\n"
"}\n"
"\n"
"/* Botones */\n"
"QPushButton, QToolButton {\n"
"    background-color: #4a8cff;\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 12px;\n"
"    padding: 10px 16px;\n"
"    font-weight: 600;\n"
"}\n"
"\n"
"QPushButton:hover, QToolButton:hover {\n"
"    background-color: #3a7af0;\n"
"}\n"
"\n"
"QPushButton:pressed, QToolButton:pressed {\n"
"    background-color: #2d67d0;\n"
"}\n"
"\n"
"QPushButton:disabled, QToolButton:disabled {\n"
"    background-color: #40516a;\n"
"    color: #bcc7d6;\n"
"}\n"
"\n"
"/* Inputs */\n"
"QLineEdit, QComboBox, QSpinBox {\n"
"    background-color: #0a1423;\n"
"    color: #e6edf7;\n"
"    border: 1px solid #385174;\n"
"    border-radius: 12px;\n"
"    padding: 8px 12px;\n"
"    min-height: 24px;\n"
"}\n"
"\n"
"QLineEdit:focus, QComboBox:focus, QSpinBox:focus {\n"
"    border: 1px solid #4a8cff;\n"
"}\n"
"\n"
"/* Combobox popup */\n"
"QComboBox::drop-down {\n"
"    border: none;\n"
"    width: 24px;\n"
"    background: transparent;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView {\n"
"    background-color: #0d1727;\n"
"    color: #e6edf7;\n"
"    border: 1px solid #2c405d;\n"
"    selection-background-color: #4a8cff;\n"
"    selection-color: white;\n"
"}\n"
"\n"
"/* Lista de imágenes */\n"
"QListWidget {\n"
"    background-color: #091426;\n"
"    color: #e6edf7;\n"
"    border: 1px solid #314866;\n"
"    border-radius: 16px;\n"
"    padding: 8px;\n"
"}\n"
"\n"
"QListWidget::item {\n"
"    background-color: #122036;\n"
"    border: 1px solid #233754;\n"
"    border-radius: 10px;\n"
"    margin: 6px;\n"
"    padding: 8px;\n"
"}\n"
"\n"
"QListWidget::item:selected {\n"
"    background-color: #1e3f79;\n"
"    border: 1px solid #4a8cff;\n"
"    color: white;\n"
"}\n"
"\n"
"/* Tabla */\n"
"QTableWidget {\n"
"    background-color: #091426;\n"
"    color: #e6edf7;\n"
"    border: 1px solid #314866;\n"
"    border-radius: 16px;\n"
"    gridline-color: #1e2d45;\n"
"    selection-background-color: #1e3f79;\n"
"    selection-color: white;\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"    background-color: #22324a;\n"
"    color: #f8fbff;\n"
"    padding: 10px;\n"
"    border: none;\n"
"    font-weight: 700;\n"
"}\n"
"\n"
"QTableCornerButton::section {\n"
"    background-color: #22324a;\n"
"    border: none;\n"
"}\n"
"\n"
"/* QTextBrowser */\n"
"QTextBrowser {\n"
"    background-color: transparent;\n"
"    color: #e6edf7;\n"
"    border: none;\n"
"    padding: 4px;\n"
"    selection-background-color: #1e3f79;\n"
"    selection-color: white;\n"
"}\n"
"\n"
"/* Scrollbars */\n"
"QScrollBar:vertical {\n"
"    background: transparent;\n"
"    width: 10px;\n"
"    margin: 4px 2px 4px 2px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical {\n"
"    background: #425978;\n"
"    border-radius: 5px;\n"
"    min-height: 30px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical:hover {\n"
"    background: #567095;\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical, QScrollBar::sub-line:vertical {\n"
"    height: 0;\n"
"}\n"
"\n"
"QScrollBar:horizontal {\n"
"    background: transparent;\n"
"    height: 10px;\n"
"    margin: 2px 4px 2px 4px;\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal {\n"
"    background: #425978;\n"
"    border-radius: 5px;\n"
"    min-width: 30px;\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal:hover {\n"
"    background: #567095;\n"
"}\n"
"\n"
"QScrollBar::add-line:horizontal, QScrollBar::sub-line:horizontal {\n"
"    width: 0;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_12.setContentsMargins(16, 16, 16, 16)
        self.verticalLayout_12.setSpacing(12)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.mainContainer = QtWidgets.QWidget(parent=self.centralwidget)
        self.mainContainer.setObjectName("mainContainer")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.mainContainer)
        self.verticalLayout_2.setSpacing(20)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.headerCard = QtWidgets.QFrame(parent=self.mainContainer)
        self.headerCard.setMinimumSize(QtCore.QSize(0, 71))
        self.headerCard.setMaximumSize(QtCore.QSize(16777215, 71))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(True)
        self.headerCard.setFont(font)
        self.headerCard.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.headerCard.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.headerCard.setObjectName("headerCard")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.headerCard)
        self.horizontalLayout.setContentsMargins(20, 5, 20, 5)
        self.horizontalLayout.setSpacing(8)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.centerHeaderContainer = QtWidgets.QWidget(parent=self.headerCard)
        self.centerHeaderContainer.setObjectName("centerHeaderContainer")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centerHeaderContainer)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.lblLogoProyecto = QtWidgets.QLabel(parent=self.centerHeaderContainer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblLogoProyecto.sizePolicy().hasHeightForWidth())
        self.lblLogoProyecto.setSizePolicy(sizePolicy)
        self.lblLogoProyecto.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(15)
        font.setBold(True)
        self.lblLogoProyecto.setFont(font)
        self.lblLogoProyecto.setScaledContents(False)
        self.lblLogoProyecto.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblLogoProyecto.setObjectName("lblLogoProyecto")
        self.verticalLayout_3.addWidget(self.lblLogoProyecto)
        self.horizontalLayout.addWidget(self.centerHeaderContainer)
        self.rightHeaderContainer = QtWidgets.QWidget(parent=self.headerCard)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rightHeaderContainer.sizePolicy().hasHeightForWidth())
        self.rightHeaderContainer.setSizePolicy(sizePolicy)
        self.rightHeaderContainer.setMaximumSize(QtCore.QSize(200, 16777215))
        self.rightHeaderContainer.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.rightHeaderContainer.setAutoFillBackground(False)
        self.rightHeaderContainer.setObjectName("rightHeaderContainer")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.rightHeaderContainer)
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetDefaultConstraint)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lblLogoInstitucion = QtWidgets.QLabel(parent=self.rightHeaderContainer)
        self.lblLogoInstitucion.setPixmap(QtGui.QPixmap("editables/../assets/Logo_EIC.png"))
        self.lblLogoInstitucion.setScaledContents(True)
        self.lblLogoInstitucion.setOpenExternalLinks(False)
        self.lblLogoInstitucion.setObjectName("lblLogoInstitucion")
        self.horizontalLayout_2.addWidget(self.lblLogoInstitucion)
        self.horizontalLayout.addWidget(self.rightHeaderContainer)
        self.verticalLayout_2.addWidget(self.headerCard)
        self.tabWidget = QtWidgets.QTabWidget(parent=self.mainContainer)
        self.tabWidget.setObjectName("tabWidget")
        self.tabPrincipal = QtWidgets.QWidget()
        self.tabPrincipal.setObjectName("tabPrincipal")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.tabPrincipal)
        self.verticalLayout.setObjectName("verticalLayout")
        self.principalContainer = QtWidgets.QWidget(parent=self.tabPrincipal)
        self.principalContainer.setObjectName("principalContainer")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.principalContainer)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.uploadCard = QtWidgets.QFrame(parent=self.principalContainer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Ignored, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uploadCard.sizePolicy().hasHeightForWidth())
        self.uploadCard.setSizePolicy(sizePolicy)
        self.uploadCard.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.uploadCard.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.uploadCard.setObjectName("uploadCard")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.uploadCard)
        self.verticalLayout_6.setContentsMargins(18, 18, 18, 18)
        self.verticalLayout_6.setSpacing(10)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.uploadHeaderRow = QtWidgets.QWidget(parent=self.uploadCard)
        self.uploadHeaderRow.setObjectName("uploadHeaderRow")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.uploadHeaderRow)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.lblUploadTitle = QtWidgets.QLabel(parent=self.uploadHeaderRow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Ignored, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblUploadTitle.sizePolicy().hasHeightForWidth())
        self.lblUploadTitle.setSizePolicy(sizePolicy)
        self.lblUploadTitle.setScaledContents(False)
        self.lblUploadTitle.setWordWrap(True)
        self.lblUploadTitle.setObjectName("lblUploadTitle")
        self.horizontalLayout_5.addWidget(self.lblUploadTitle)
        self.btnCargarImagenes = QtWidgets.QPushButton(parent=self.uploadHeaderRow)
        self.btnCargarImagenes.setObjectName("btnCargarImagenes")
        self.horizontalLayout_5.addWidget(self.btnCargarImagenes)
        self.verticalLayout_6.addWidget(self.uploadHeaderRow)
        self.lblUploadHint = QtWidgets.QLabel(parent=self.uploadCard)
        self.lblUploadHint.setScaledContents(False)
        self.lblUploadHint.setWordWrap(True)
        self.lblUploadHint.setObjectName("lblUploadHint")
        self.verticalLayout_6.addWidget(self.lblUploadHint)
        self.listImagenes = QtWidgets.QListWidget(parent=self.uploadCard)
        self.listImagenes.setSelectionMode(QtWidgets.QAbstractItemView.SelectionMode.ExtendedSelection)
        self.listImagenes.setIconSize(QtCore.QSize(120, 120))
        self.listImagenes.setMovement(QtWidgets.QListView.Movement.Static)
        self.listImagenes.setResizeMode(QtWidgets.QListView.ResizeMode.Adjust)
        self.listImagenes.setGridSize(QtCore.QSize(150, 150))
        self.listImagenes.setViewMode(QtWidgets.QListView.ViewMode.IconMode)
        self.listImagenes.setObjectName("listImagenes")
        self.verticalLayout_6.addWidget(self.listImagenes)
        self.uploadFooterRow = QtWidgets.QWidget(parent=self.uploadCard)
        self.uploadFooterRow.setObjectName("uploadFooterRow")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.uploadFooterRow)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.btnEliminarImagen = QtWidgets.QPushButton(parent=self.uploadFooterRow)
        self.btnEliminarImagen.setObjectName("btnEliminarImagen")
        self.horizontalLayout_6.addWidget(self.btnEliminarImagen)
        self.btnLimpiarLista = QtWidgets.QPushButton(parent=self.uploadFooterRow)
        self.btnLimpiarLista.setObjectName("btnLimpiarLista")
        self.horizontalLayout_6.addWidget(self.btnLimpiarLista)
        self.lblCantidadImagenes = QtWidgets.QLabel(parent=self.uploadFooterRow)
        self.lblCantidadImagenes.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.lblCantidadImagenes.setWordWrap(False)
        self.lblCantidadImagenes.setObjectName("lblCantidadImagenes")
        self.horizontalLayout_6.addWidget(self.lblCantidadImagenes)
        self.verticalLayout_6.addWidget(self.uploadFooterRow)
        self.statsRow = QtWidgets.QWidget(parent=self.uploadCard)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.statsRow.sizePolicy().hasHeightForWidth())
        self.statsRow.setSizePolicy(sizePolicy)
        self.statsRow.setObjectName("statsRow")
        self.formLayout = QtWidgets.QFormLayout(self.statsRow)
        self.formLayout.setObjectName("formLayout")
        self.lblTiempoTitulo = QtWidgets.QLabel(parent=self.statsRow)
        self.lblTiempoTitulo.setObjectName("lblTiempoTitulo")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.lblTiempoTitulo)
        self.lblRutaTitulo = QtWidgets.QLabel(parent=self.statsRow)
        self.lblRutaTitulo.setObjectName("lblRutaTitulo")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.lblRutaTitulo)
        self.txtTiempoEjecucion = QtWidgets.QLineEdit(parent=self.statsRow)
        self.txtTiempoEjecucion.setText("")
        self.txtTiempoEjecucion.setReadOnly(True)
        self.txtTiempoEjecucion.setObjectName("txtTiempoEjecucion")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.txtTiempoEjecucion)
        self.txtRutaGuardado = QtWidgets.QLineEdit(parent=self.statsRow)
        self.txtRutaGuardado.setText("")
        self.txtRutaGuardado.setObjectName("txtRutaGuardado")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.txtRutaGuardado)
        self.lblNumberThreads = QtWidgets.QLabel(parent=self.statsRow)
        self.lblNumberThreads.setObjectName("lblNumberThreads")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.LabelRole, self.lblNumberThreads)
        self.txtNumberThreads = QtWidgets.QSpinBox(parent=self.statsRow)
        self.txtNumberThreads.setMinimum(1)
        self.txtNumberThreads.setMaximum(1000000000)
        self.txtNumberThreads.setProperty("value", 12)
        self.txtNumberThreads.setObjectName("txtNumberThreads")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.FieldRole, self.txtNumberThreads)
        self.verticalLayout_6.addWidget(self.statsRow)
        self.horizontalLayout_4.addWidget(self.uploadCard)
        self.rulesCard = QtWidgets.QFrame(parent=self.principalContainer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rulesCard.sizePolicy().hasHeightForWidth())
        self.rulesCard.setSizePolicy(sizePolicy)
        self.rulesCard.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.rulesCard.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.rulesCard.setObjectName("rulesCard")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.rulesCard)
        self.verticalLayout_7.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetDefaultConstraint)
        self.verticalLayout_7.setSpacing(6)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.rulesHeaderRow = QtWidgets.QWidget(parent=self.rulesCard)
        self.rulesHeaderRow.setObjectName("rulesHeaderRow")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.rulesHeaderRow)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.lblRulesTitle = QtWidgets.QLabel(parent=self.rulesHeaderRow)
        self.lblRulesTitle.setObjectName("lblRulesTitle")
        self.horizontalLayout_7.addWidget(self.lblRulesTitle)
        self.verticalLayout_7.addWidget(self.rulesHeaderRow)
        self.rulesTable = QtWidgets.QTableWidget(parent=self.rulesCard)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rulesTable.sizePolicy().hasHeightForWidth())
        self.rulesTable.setSizePolicy(sizePolicy)
        self.rulesTable.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.rulesTable.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAsNeeded)
        self.rulesTable.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.SizeAdjustPolicy.AdjustIgnored)
        self.rulesTable.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers)
        self.rulesTable.setAlternatingRowColors(True)
        self.rulesTable.setSelectionMode(QtWidgets.QAbstractItemView.SelectionMode.ExtendedSelection)
        self.rulesTable.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectionBehavior.SelectRows)
        self.rulesTable.setColumnCount(4)
        self.rulesTable.setObjectName("rulesTable")
        self.rulesTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.rulesTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.rulesTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.rulesTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.rulesTable.setHorizontalHeaderItem(3, item)
        self.rulesTable.horizontalHeader().setCascadingSectionResizes(False)
        self.rulesTable.horizontalHeader().setDefaultSectionSize(155)
        self.rulesTable.horizontalHeader().setStretchLastSection(False)
        self.verticalLayout_7.addWidget(self.rulesTable)
        self.ruleEditorCard = QtWidgets.QFrame(parent=self.rulesCard)
        self.ruleEditorCard.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.ruleEditorCard.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.ruleEditorCard.setObjectName("ruleEditorCard")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.ruleEditorCard)
        self.verticalLayout_8.setContentsMargins(18, 18, 18, 18)
        self.verticalLayout_8.setSpacing(10)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.lblRuleEditorTitle = QtWidgets.QLabel(parent=self.ruleEditorCard)
        self.lblRuleEditorTitle.setObjectName("lblRuleEditorTitle")
        self.verticalLayout_8.addWidget(self.lblRuleEditorTitle)
        self.ruleEditorGrid = QtWidgets.QGridLayout()
        self.ruleEditorGrid.setHorizontalSpacing(14)
        self.ruleEditorGrid.setVerticalSpacing(8)
        self.ruleEditorGrid.setObjectName("ruleEditorGrid")
        self.lblColColor = QtWidgets.QLabel(parent=self.ruleEditorCard)
        self.lblColColor.setObjectName("lblColColor")
        self.ruleEditorGrid.addWidget(self.lblColColor, 0, 0, 1, 1)
        self.lblColValor = QtWidgets.QLabel(parent=self.ruleEditorCard)
        self.lblColValor.setObjectName("lblColValor")
        self.ruleEditorGrid.addWidget(self.lblColValor, 0, 2, 1, 1)
        self.lblColEfecto = QtWidgets.QLabel(parent=self.ruleEditorCard)
        self.lblColEfecto.setObjectName("lblColEfecto")
        self.ruleEditorGrid.addWidget(self.lblColEfecto, 0, 1, 1, 1)
        self.stackedValor = QtWidgets.QStackedWidget(parent=self.ruleEditorCard)
        self.stackedValor.setAutoFillBackground(False)
        self.stackedValor.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.stackedValor.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.stackedValor.setLineWidth(1)
        self.stackedValor.setObjectName("stackedValor")
        self.pageValorInvertir = QtWidgets.QWidget()
        self.pageValorInvertir.setObjectName("pageValorInvertir")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.pageValorInvertir)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.cmbGiro = QtWidgets.QComboBox(parent=self.pageValorInvertir)
        self.cmbGiro.setObjectName("cmbGiro")
        self.cmbGiro.addItem("")
        self.cmbGiro.addItem("")
        self.cmbGiro.addItem("")
        self.verticalLayout_11.addWidget(self.cmbGiro)
        self.stackedValor.addWidget(self.pageValorInvertir)
        self.pageValorDesenfoque = QtWidgets.QWidget()
        self.pageValorDesenfoque.setObjectName("pageValorDesenfoque")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.pageValorDesenfoque)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.spinKernel = QtWidgets.QSpinBox(parent=self.pageValorDesenfoque)
        self.spinKernel.setMinimum(1)
        self.spinKernel.setMaximum(999)
        self.spinKernel.setProperty("value", 34)
        self.spinKernel.setObjectName("spinKernel")
        self.verticalLayout_10.addWidget(self.spinKernel)
        self.stackedValor.addWidget(self.pageValorDesenfoque)
        self.ruleEditorGrid.addWidget(self.stackedValor, 1, 2, 1, 1)
        self.cmbEfecto = QtWidgets.QComboBox(parent=self.ruleEditorCard)
        self.cmbEfecto.setObjectName("cmbEfecto")
        self.cmbEfecto.addItem("")
        self.cmbEfecto.addItem("")
        self.ruleEditorGrid.addWidget(self.cmbEfecto, 1, 1, 1, 1)
        self.btnSeleccionColor = QtWidgets.QPushButton(parent=self.ruleEditorCard)
        self.btnSeleccionColor.setObjectName("btnSeleccionColor")
        self.ruleEditorGrid.addWidget(self.btnSeleccionColor, 1, 0, 1, 1)
        self.ruleEditorGrid.setColumnStretch(0, 2)
        self.ruleEditorGrid.setColumnStretch(1, 2)
        self.ruleEditorGrid.setColumnStretch(2, 3)
        self.verticalLayout_8.addLayout(self.ruleEditorGrid)
        self.ruleButtonsRow = QtWidgets.QWidget(parent=self.ruleEditorCard)
        self.ruleButtonsRow.setObjectName("ruleButtonsRow")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.ruleButtonsRow)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.btnAgregarRegla = QtWidgets.QPushButton(parent=self.ruleButtonsRow)
        self.btnAgregarRegla.setObjectName("btnAgregarRegla")
        self.horizontalLayout_8.addWidget(self.btnAgregarRegla)
        self.btnEditarRegla = QtWidgets.QPushButton(parent=self.ruleButtonsRow)
        self.btnEditarRegla.setObjectName("btnEditarRegla")
        self.horizontalLayout_8.addWidget(self.btnEditarRegla)
        self.btnEliminarRegla = QtWidgets.QPushButton(parent=self.ruleButtonsRow)
        self.btnEliminarRegla.setObjectName("btnEliminarRegla")
        self.horizontalLayout_8.addWidget(self.btnEliminarRegla)
        self.verticalLayout_8.addWidget(self.ruleButtonsRow)
        self.lblPreviewNombre = QtWidgets.QLabel(parent=self.ruleEditorCard)
        self.lblPreviewNombre.setWordWrap(True)
        self.lblPreviewNombre.setObjectName("lblPreviewNombre")
        self.verticalLayout_8.addWidget(self.lblPreviewNombre)
        self.verticalLayout_7.addWidget(self.ruleEditorCard)
        self.executionArea = QtWidgets.QFrame(parent=self.rulesCard)
        self.executionArea.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.executionArea.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.executionArea.setObjectName("executionArea")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.executionArea)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.lblSeleccionImagenesTitulo = QtWidgets.QLabel(parent=self.executionArea)
        self.lblSeleccionImagenesTitulo.setObjectName("lblSeleccionImagenesTitulo")
        self.verticalLayout_9.addWidget(self.lblSeleccionImagenesTitulo)
        self.widget = QtWidgets.QWidget(parent=self.executionArea)
        self.widget.setObjectName("widget")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.btnSeleccionarImagenesDestino = QtWidgets.QToolButton(parent=self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnSeleccionarImagenesDestino.sizePolicy().hasHeightForWidth())
        self.btnSeleccionarImagenesDestino.setSizePolicy(sizePolicy)
        self.btnSeleccionarImagenesDestino.setMinimumSize(QtCore.QSize(0, 40))
        self.btnSeleccionarImagenesDestino.setPopupMode(QtWidgets.QToolButton.ToolButtonPopupMode.MenuButtonPopup)
        self.btnSeleccionarImagenesDestino.setObjectName("btnSeleccionarImagenesDestino")
        self.horizontalLayout_10.addWidget(self.btnSeleccionarImagenesDestino)
        self.label = QtWidgets.QLabel(parent=self.widget)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label.setObjectName("label")
        self.horizontalLayout_10.addWidget(self.label)
        self.verticalLayout_9.addWidget(self.widget)
        self.btnEjecutarPrograma = QtWidgets.QPushButton(parent=self.executionArea)
        self.btnEjecutarPrograma.setMinimumSize(QtCore.QSize(0, 46))
        self.btnEjecutarPrograma.setObjectName("btnEjecutarPrograma")
        self.verticalLayout_9.addWidget(self.btnEjecutarPrograma)
        self.verticalLayout_7.addWidget(self.executionArea)
        self.horizontalLayout_4.addWidget(self.rulesCard)
        self.horizontalLayout_4.setStretch(0, 5)
        self.horizontalLayout_4.setStretch(1, 7)
        self.verticalLayout.addWidget(self.principalContainer)
        self.tabWidget.addTab(self.tabPrincipal, "")
        self.tabAcercaDe = QtWidgets.QWidget()
        self.tabAcercaDe.setObjectName("tabAcercaDe")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.tabAcercaDe)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.aboutContainer = QtWidgets.QWidget(parent=self.tabAcercaDe)
        self.aboutContainer.setObjectName("aboutContainer")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.aboutContainer)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.aboutHeaderCard = QtWidgets.QFrame(parent=self.aboutContainer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.aboutHeaderCard.sizePolicy().hasHeightForWidth())
        self.aboutHeaderCard.setSizePolicy(sizePolicy)
        self.aboutHeaderCard.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.aboutHeaderCard.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.aboutHeaderCard.setObjectName("aboutHeaderCard")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.aboutHeaderCard)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.aboutLeftSpacer = QtWidgets.QWidget(parent=self.aboutHeaderCard)
        self.aboutLeftSpacer.setObjectName("aboutLeftSpacer")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.aboutLeftSpacer)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.horizontalLayout_3.addWidget(self.aboutLeftSpacer)
        self.aboutTitleContainer = QtWidgets.QWidget(parent=self.aboutHeaderCard)
        self.aboutTitleContainer.setObjectName("aboutTitleContainer")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.aboutTitleContainer)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.lblAboutTitle = QtWidgets.QLabel(parent=self.aboutTitleContainer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblAboutTitle.sizePolicy().hasHeightForWidth())
        self.lblAboutTitle.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(15)
        font.setBold(True)
        self.lblAboutTitle.setFont(font)
        self.lblAboutTitle.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblAboutTitle.setObjectName("lblAboutTitle")
        self.verticalLayout_17.addWidget(self.lblAboutTitle)
        self.horizontalLayout_3.addWidget(self.aboutTitleContainer)
        self.aboutRightContainer = QtWidgets.QWidget(parent=self.aboutHeaderCard)
        self.aboutRightContainer.setObjectName("aboutRightContainer")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.aboutRightContainer)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem)
        self.lblLogoInstitucionAbout = QtWidgets.QLabel(parent=self.aboutRightContainer)
        self.lblLogoInstitucionAbout.setMinimumSize(QtCore.QSize(40, 40))
        self.lblLogoInstitucionAbout.setMaximumSize(QtCore.QSize(40, 40))
        self.lblLogoInstitucionAbout.setText("")
        self.lblLogoInstitucionAbout.setPixmap(QtGui.QPixmap("editables/../assets/logo_tec.png"))
        self.lblLogoInstitucionAbout.setScaledContents(True)
        self.lblLogoInstitucionAbout.setObjectName("lblLogoInstitucionAbout")
        self.horizontalLayout_9.addWidget(self.lblLogoInstitucionAbout)
        self.horizontalLayout_3.addWidget(self.aboutRightContainer)
        self.verticalLayout_14.addWidget(self.aboutHeaderCard)
        self.cardProyecto = QtWidgets.QFrame(parent=self.aboutContainer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cardProyecto.sizePolicy().hasHeightForWidth())
        self.cardProyecto.setSizePolicy(sizePolicy)
        self.cardProyecto.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.cardProyecto.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.cardProyecto.setObjectName("cardProyecto")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.cardProyecto)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.lblProyectoInfo = QtWidgets.QLabel(parent=self.cardProyecto)
        self.lblProyectoInfo.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(15)
        font.setBold(True)
        font.setItalic(True)
        self.lblProyectoInfo.setFont(font)
        self.lblProyectoInfo.setObjectName("lblProyectoInfo")
        self.verticalLayout_4.addWidget(self.lblProyectoInfo)
        self.txtProyectoInfo = QtWidgets.QTextBrowser(parent=self.cardProyecto)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtProyectoInfo.sizePolicy().hasHeightForWidth())
        self.txtProyectoInfo.setSizePolicy(sizePolicy)
        self.txtProyectoInfo.setMinimumSize(QtCore.QSize(0, 210))
        self.txtProyectoInfo.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.txtProyectoInfo.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.SizeAdjustPolicy.AdjustToContents)
        self.txtProyectoInfo.setObjectName("txtProyectoInfo")
        self.verticalLayout_4.addWidget(self.txtProyectoInfo)
        self.verticalLayout_14.addWidget(self.cardProyecto)
        self.cardEquipo = QtWidgets.QFrame(parent=self.aboutContainer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cardEquipo.sizePolicy().hasHeightForWidth())
        self.cardEquipo.setSizePolicy(sizePolicy)
        self.cardEquipo.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.cardEquipo.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.cardEquipo.setObjectName("cardEquipo")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.cardEquipo)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.lblEquipo = QtWidgets.QLabel(parent=self.cardEquipo)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblEquipo.sizePolicy().hasHeightForWidth())
        self.lblEquipo.setSizePolicy(sizePolicy)
        self.lblEquipo.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(15)
        font.setBold(True)
        font.setItalic(True)
        self.lblEquipo.setFont(font)
        self.lblEquipo.setObjectName("lblEquipo")
        self.verticalLayout_15.addWidget(self.lblEquipo)
        self.txtEquipo = QtWidgets.QTextBrowser(parent=self.cardEquipo)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtEquipo.sizePolicy().hasHeightForWidth())
        self.txtEquipo.setSizePolicy(sizePolicy)
        self.txtEquipo.setMinimumSize(QtCore.QSize(0, 0))
        self.txtEquipo.setMaximumSize(QtCore.QSize(16777215, 180))
        self.txtEquipo.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAsNeeded)
        self.txtEquipo.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.SizeAdjustPolicy.AdjustIgnored)
        self.txtEquipo.setAutoFormatting(QtWidgets.QTextEdit.AutoFormattingFlag.AutoNone)
        self.txtEquipo.setTabChangesFocus(False)
        self.txtEquipo.setUndoRedoEnabled(False)
        self.txtEquipo.setOverwriteMode(False)
        self.txtEquipo.setTabStopDistance(80.0)
        self.txtEquipo.setObjectName("txtEquipo")
        self.verticalLayout_15.addWidget(self.txtEquipo)
        self.verticalLayout_14.addWidget(self.cardEquipo)
        self.verticalLayout_13.addWidget(self.aboutContainer)
        self.tabWidget.addTab(self.tabAcercaDe, "")
        self.verticalLayout_2.addWidget(self.tabWidget)
        self.verticalLayout_12.addWidget(self.mainContainer)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.stackedValor.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "PixFarm"))
        self.lblLogoProyecto.setText(_translate("MainWindow", "PixFarm"))
        self.lblUploadTitle.setText(_translate("MainWindow", "Imágenes de Entrada"))
        self.btnCargarImagenes.setText(_translate("MainWindow", "Cargar"))
        self.lblUploadHint.setText(_translate("MainWindow", "Formato: BMP. Puedes arrastrar archivos o cargarlos manualmente."))
        self.btnEliminarImagen.setText(_translate("MainWindow", "Eliminar Imagen"))
        self.btnLimpiarLista.setText(_translate("MainWindow", "Limpiar Lista"))
        self.lblCantidadImagenes.setText(_translate("MainWindow", "0 imágenes"))
        self.lblTiempoTitulo.setText(_translate("MainWindow", "Tiempo de ejecución"))
        self.lblRutaTitulo.setText(_translate("MainWindow", "Ruta de guardado"))
        self.txtTiempoEjecucion.setPlaceholderText(_translate("MainWindow", "Vacío"))
        self.txtRutaGuardado.setPlaceholderText(_translate("MainWindow", "Seleccionar"))
        self.lblNumberThreads.setText(_translate("MainWindow", "Número de Threads"))
        self.lblRulesTitle.setText(_translate("MainWindow", "Transformación de Imágenes"))
        self.rulesTable.setSortingEnabled(False)
        item = self.rulesTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Color"))
        item = self.rulesTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Efecto"))
        item = self.rulesTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Valor"))
        item = self.rulesTable.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Resumen"))
        self.lblRuleEditorTitle.setText(_translate("MainWindow", "Definición de Reglas"))
        self.lblColColor.setText(_translate("MainWindow", "Color"))
        self.lblColValor.setText(_translate("MainWindow", "Variable"))
        self.lblColEfecto.setText(_translate("MainWindow", "Efecto"))
        self.cmbGiro.setItemText(0, _translate("MainWindow", "Giro Espejo"))
        self.cmbGiro.setItemText(1, _translate("MainWindow", "Giro Vertical"))
        self.cmbGiro.setItemText(2, _translate("MainWindow", "Giro Vertical Espejo"))
        self.cmbEfecto.setItemText(0, _translate("MainWindow", "Invertir imagen"))
        self.cmbEfecto.setItemText(1, _translate("MainWindow", "Desenfocado"))
        self.btnSeleccionColor.setText(_translate("MainWindow", "Seleccionar color"))
        self.btnAgregarRegla.setText(_translate("MainWindow", "Agregar regla"))
        self.btnEditarRegla.setText(_translate("MainWindow", "Editar regla"))
        self.btnEliminarRegla.setText(_translate("MainWindow", "Eliminar regla"))
        self.lblPreviewNombre.setText(_translate("MainWindow", "Nombre de salida: ---"))
        self.lblSeleccionImagenesTitulo.setText(_translate("MainWindow", "Imágenes a transformar"))
        self.btnSeleccionarImagenesDestino.setText(_translate("MainWindow", "Seleccionar imágenes..."))
        self.label.setText(_translate("MainWindow", "No se seleccionaron imágenes."))
        self.btnEjecutarPrograma.setText(_translate("MainWindow", "Ejecutar"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabPrincipal), _translate("MainWindow", "Transformador"))
        self.lblAboutTitle.setText(_translate("MainWindow", "Acerca del Proyecto"))
        self.lblProyectoInfo.setText(_translate("MainWindow", "Información del Proyecto"))
        self.txtProyectoInfo.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Adwaita Sans\'; font-weight:700;\">Clase:</span><span style=\" font-family:\'Adwaita Sans\';\"> Implementación de redes de área amplia y servicios distribuidos</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Adwaita Sans\'; font-weight:700;\">Grupo: </span><span style=\" font-family:\'Adwaita Sans\';\">501</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Adwaita Sans\'; font-weight:700;\">Código: </span><span style=\" font-family:\'Adwaita Sans\';\">TC3003B.501</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Adwaita Sans\'; font-weight:700;\">Versión del Proyecto: </span><span style=\" font-family:\'Adwaita Sans\';\">1.1.0</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Adwaita Sans\';\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Adwaita Sans\'; font-weight:700;\">Descripción: </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Adwaita Sans\';\">Este proyecto consiste en el desarrollo de una plataforma para la transformación y procesamiento distribuido de imágenes, apoyada en una granja de computadoras que permite ejecutar tareas de manera paralela y escalable. La aplicación ofrece herramientas para la carga, selección y configuración de reglas de transformación sobre imágenes digitales, optimizando el uso de recursos computacionales y disminuyendo el tiempo requerido para procesar grandes volúmenes de datos.</span></p></body></html>"))
        self.lblEquipo.setText(_translate("MainWindow", "Información del Equipo"))
        self.txtEquipo.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Adwaita Sans\'; font-weight:700;\">Integrantes:</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Adwaita Sans\'; font-weight:700;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Adwaita Sans\';\">- Abigail Pérez García | A01736815</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Adwaita Sans\';\">- Alvaro Alberto Cruz Jiménez | A01737453</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Adwaita Sans\';\">- Humberto Pérez Galindo | A01732526</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Adwaita Sans\';\">- Rodrigo López Guerra | A01737437</span></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabAcercaDe), _translate("MainWindow", "Acerca de"))
